server:
  port: 8082

spring:
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.163.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: UTF-8
    # 授权码 (再开通邮箱服务时获得)
    password: ECLSTPEGMDRDSQGA
    # 发送者邮箱地址
    username: 13337322686@163.com
    # 端口(不同邮箱端口不一样)
    port: 25

  # rabbitmq 配置
  rabbitmq:
    # 用户名称
    username: admin
    # 用户密码
    password: admin
    # 服务器地址
    host: 192.168.31.128
    # 端口号
    port: 5672
